services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - blog-network
    env_file:
      - ./.env
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    command:
      ["sh", "-c", "sleep 3 && uvicorn main:app --host 0.0.0.0 --port 8000"]
    networks:
      - blog-network
      - npm-shared
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - blog-network
      - npm-shared
networks:
  blog-network:
    driver: bridge
  npm-shared:
    external: true
volumes:
  db-data:
    labels:
      com.docker.compose.volume: db-data
