name: Deploy to Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd projects/blog
            echo "Pulling Latest code from GitHub"
            git pull origin main
            sudo docker-compose down
            sudo docker-compose build
            sudo docker-compose up -d 
            sudo docker system prune -f --filter "label!=com.docker.com.compose.volume=db-data"
